// Generated by CoffeeScript 1.4.0

exports.index = function(req, res) {
  return res.render("index", {
    title: "Hola mundo"
  });
};

exports.lista = function(req, res) {
  return res.render("lista", {
    title: "Lista de Datos"
  });
};
